version: "3.8"


services:

  backend:
    image: tgshop/backend
    container_name: tgshop_backend
    restart: always
    networks:
      - tgshop
    depends_on:
      - migration
      - database
      - proxy

  balancer:
    image: tgshop/balancer
    container_name: tgshop_balancer
    restart: always
    networks:
      - tgshop
    depends_on:
      - backend

  database:
    image: tgshop/database
    container_name: tgshop_database
    restart: always
    networks:
      - tgshop
    env_file:
      - ./envs/database
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: database-conf
        target: /etc/mysql
        volume:
          nocopy: false
      - type: volume
        source: database-logs
        target: /var/log/mysql
        volume:
          nocopy: true      
      - type: volume
        source: database-data
        target: /var/lib/mysql
        volume:
          nocopy: true

  migration:
    image: tgshop/migration
    container_name: tgshop_migration
    networks:
      - tgshop
    depends_on:
      - database

  proxy:
    image: tgshop/proxy
    container_name: tgshop_proxy
    restart: always
    networks:
      - tgshop
    ports:
      - 80:80
    volumes:
      - type: volume
        source: proxy-conf
        target: /etc/nginx
        volume:
          nocopy: false
      - type: volume
        source: proxy-logs
        target: /var/log/nginx
        volume:
          nocopy: true

  worker:
    image: tgshop/worker
    container_name: tgshop_worker
    restart: always
    networks:
      - tgshop
    depends_on:
      - balancer


volumes:

  # database:mariadb
  database-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/database/conf
  database-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/database/logs
  database-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/database/data

  # proxy:nginx
  proxy-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/proxy/conf
  proxy-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/proxy/logs


networks:

  tgshop:
    name: tgshop
