version: "3.8"


services:

  database:
    image: tgshop/database
    container_name: tgshop_database
    restart: always
    healthcheck:
      test: [ "CMD", "/bin/bash", "/healthcheck.sh" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    networks:
      - tgshop
    env_file:
      - ./envs/database
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: database-conf
        target: /etc/mysql
        volume:
          nocopy: false
      - type: volume
        source: database-logs
        target: /var/log/mysql
        volume:
          nocopy: true      
      - type: volume
        source: database-data
        target: /var/lib/mysql
        volume:
          nocopy: true

  migration:
    image: tgshop/migration
    container_name: tgshop_migration
    env_file:
      - ./envs/database
    networks:
      - tgshop
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - type: volume
        source: migration-data
        target: /app/alembic/versions
        volume:
          nocopy: true

volumes:

  # database:mariadb
  database-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/database/conf
  database-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/database/logs
  database-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/database/data

  # migration:alembic
  migration-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.volumes/migration/data


networks:

  tgshop:
    name: tgshop
