version: "3.8"

services:

  backend:
    image: tgshop/backend
    container_name: tgshop_backend
    networks:
      - tgshop

  database:
    image: tgshop/database
    container_name: tgshop_database
    networks:
      - tgshop

  reverse-proxy:
    image: tgshop/reverse-proxy
    container_name: tgshop_reverse-proxy
    networks:
      - tgshop

  worker:
    image: tgshop/worker
    container_name: tgshop_worker
    networks:
      - tgshop

  workers-balancer:
    image: tgshop/workers-balancer
    container_name: tgshop_workers-balancer
    networks:
      - tgshop

volumes:

networks:
  tgshop:
    name: tgshop